[WIP] Initial implementation
MyCryptoHQ/gas-estimation pull request #1
Opened 2021-09-15 11:27 UTC by FrederikBolding

2021-09-16 12:41 UTC, FrederikBolding commented
[sc-8981]

2021-09-17 11:03 UTC, Mrtenz approved these changes

2021-09-17 11:03 UTC, Mrtenz commented on src/eip1559.ts
> +  }, [] as bigint[]);
Use `reduce` generic parameter instead.

2021-09-17 11:03 UTC, Mrtenz requested changes
Did not mean to approve

2021-09-17 11:05 UTC, FrederikBolding commented on src/eip1559.ts
> +  }, [] as bigint[]);
Fixed!

2021-09-17 11:09 UTC, Mrtenz approved these changes

2021-09-17 11:09 UTC, merged